# -*- coding: utf-8 -*-
"""14-Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AT3XLxroBtvM-ZyCAHYJSIcTJ0sIQ5vg
"""

import numpy as np
a = np.array([2,6,1,9,10,3,27])
print(a)
x = []
def maxvalue(a):
  for i in a:
    if ( i%2!=0):
      x.append(i)
maxvalue(a)
print(x)
##print(list2)